stages:
  - deploy

deploy_to_server:
  stage: deploy
  script:
    - ssh -oStrictHostKeyChecking=no -i "C:\Users\royha\.ssh\id_ed25519" azureuser@20.6.73.92 'cd /projects/testproject && git pull origin master && ./deploy.sh'
  only:
    - master
